theme: minima
title: Personal Blog
author:
  name: Elias Kaspar Ladenburger
  email: "blog@eliasladenburger.com": 
description: A wild mishmash of topics around tech, good communication, freelancing, building communities and being a good person.
